# NumPy — Computación Numérica en Python

## ¿Qué es NumPy?

**NumPy** (Numerical Python) es la librería fundamental para computación científica en Python. Proporciona:

- Un objeto de arreglo (array) multidimensional de alto rendimiento
- Herramientas para trabajar con estos arreglos
- Funciones matemáticas, lógicas, de ordenamiento, estadísticas, y más

## ¿Para qué sirve?

| Tarea | Sin NumPy | Con NumPy |
|---|---|---|
| Sumar dos listas de 1 millón de elementos | ~0.5 segundos | ~0.005 segundos |
| Multiplicar matrices | Código complejo con loops | Una línea |
| Operaciones matemáticas | Loop por cada elemento | Operaciones vectorizadas |

NumPy es la base de casi todas las librerías de ciencia de datos: Pandas, Matplotlib, Scikit-learn, etc.

## Instalación e Importación

Para instalar NumPy (si no está instalado):
```bash
pip install numpy
```

Por convención, se importa con el alias `np`:

In [1]:
import numpy as np

print("NumPy versión:", np.__version__)

NumPy versión: 2.0.2


---
## Nivel 1 — Conceptos Básicos: Arrays

### ¿Qué diferencia hay entre una lista de Python y un array de NumPy?

In [2]:
# Lista de Python
lista = [1, 2, 3, 4, 5]
print("Lista Python:", lista)
print("Tipo:", type(lista))

print()

# Array de NumPy
arreglo = np.array([1, 2, 3, 4, 5])
print("Array NumPy:", arreglo)
print("Tipo:", type(arreglo))

Lista Python: [1, 2, 3, 4, 5]
Tipo: <class 'list'>

Array NumPy: [1 2 3 4 5]
Tipo: <class 'numpy.ndarray'>


In [3]:
# La diferencia clave: operaciones elemento a elemento
lista_python = [1, 2, 3]

# Con listas, el operador * repite la lista
print("Lista * 3:", lista_python * 3)  # [1, 2, 3, 1, 2, 3, 1, 2, 3]

arreglo_np = np.array([1, 2, 3])

# Con NumPy, * multiplica cada elemento
print("Array * 3:", arreglo_np * 3)   # [3, 6, 9]

Lista * 3: [1, 2, 3, 1, 2, 3, 1, 2, 3]
Array * 3: [3 6 9]


### ¿Por qué NumPy es tan rápido? — Comparación de rendimiento

NumPy implementa las operaciones sobre arrays en **código C precompilado**. La misma operación que requiere un ciclo `for` en Python se ejecuta internamente sin ciclos explícitos. Esto se conoce como *código vectorizado* (Stewart & Mommert, §4.1).

In [4]:
import time

N = 10_000_000   # 10 millones de elementos

# ── Enfoque con lista Python ──────────────────────────────────────────────────
a_lista = list(range(N))
t0 = time.time()
b_lista = []
for i in range(len(a_lista)):
    b_lista.append(a_lista[i] + 1)
t_lista = time.time() - t0

# ── Enfoque con array NumPy ───────────────────────────────────────────────────
a_np = np.array(a_lista)
t0 = time.time()
b_np = a_np + 1          # ← una sola línea, sin ciclo explícito
t_numpy = time.time() - t0

print(f"Lista Python : {t_lista:.3f} segundos")
print(f"Array NumPy  : {t_numpy:.3f} segundos")
print(f"NumPy es {t_lista / t_numpy:.0f}× más rápido")

Lista Python : 0.868 segundos
Array NumPy  : 0.015 segundos
NumPy es 59× más rápido


### Crear arrays de diferentes formas

In [5]:
# Array de ceros y unos
ceros = np.zeros(5)
unos  = np.ones(5)
vacio = np.empty(5)   # sin inicializar — muy rápido, valores arbitrarios
print("Ceros:", ceros)
print("Unos :", unos)
print("Vacío:", vacio)

# Array con rango (como range(), pero retorna array)
rango = np.arange(0, 10, 2)          # inicio, fin (exclusivo), paso
print("\nArange (0 a 10, paso 2):", rango)

# N valores igualmente espaciados — escala lineal
espacio = np.linspace(0, 1, 6)       # inicio, fin (inclusivo), N puntos
print("Linspace (6 puntos entre 0 y 1):", espacio)

# N valores en escala logarítmica (base 10 por defecto)
log_esp = np.logspace(0, 3, 4)       # 10^0 a 10^3, 4 valores
print("Logspace (10^0 a 10^3):", log_esp)

# Constructores "look-alike": misma forma que otro array
base = np.array([1, 2, 3, 4, 5])
print("\nzeros_like(base):", np.zeros_like(base))
print("ones_like(base) :", np.ones_like(base))

Ceros: [0. 0. 0. 0. 0.]
Unos : [1. 1. 1. 1. 1.]
Vacío: [4.68773059e-315 0.00000000e+000 6.89971153e-310 5.78295538e-317
 2.37151510e-322]

Arange (0 a 10, paso 2): [0 2 4 6 8]
Linspace (6 puntos entre 0 y 1): [0.  0.2 0.4 0.6 0.8 1. ]
Logspace (10^0 a 10^3): [   1.   10.  100. 1000.]

zeros_like(base): [0 0 0 0 0]
ones_like(base) : [1 1 1 1 1]


In [6]:
print(base.shape)
print(base.ndim)

(5,)
1


### Arrays 2D (matrices)

In [7]:
# Crear una matriz 2D
matriz = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Matriz:")
print(matriz)
print("\nForma (filas x columnas):", matriz.shape)
print("Número de dimensiones:", matriz.ndim)
print("Total de elementos:", matriz.size)
print("Tipo de dato:", matriz.dtype)

Matriz:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Forma (filas x columnas): (3, 3)
Número de dimensiones: 2
Total de elementos: 9
Tipo de dato: int64


### Tipos de datos (`dtype`) y atributos del array

Todos los elementos de un array NumPy tienen el **mismo tipo de dato** (`dtype`). NumPy infiere el tipo al crear el array, pero puedes especificarlo. Tipos comunes: `int64`, `float64`, `complex128`, `bool`. Puedes convertir con `.astype()` (Stewart & Mommert, §4.1.1).

In [8]:
x = np.array([1, 2, 3.268999])         # Python convierte todo a float64
print("dtype inferido:", x.dtype)

# Especificar dtype manualmente
x_int  = np.array([1.5566666666, 2, 3], dtype=int)
x_cpx  = np.array([1, 2, 3], dtype=complex)
print("dtype=int    :", x_int,  "→", x_int.dtype)
print("dtype=complex:", x_cpx, "→", x_cpx.dtype)

# Convertir dtype con astype()
x_float = x_int.astype(float)
print("\nx_int.astype(float):", x_float, "→", x_float.dtype)

# Atributos importantes de un array
m = np.array([[1, 2, 3], [4, 5, 6]])
print("\nArray m:")
print(m)
print("  ndim :", m.ndim)    # número de dimensiones
print("  shape:", m.shape)   # (filas, columnas)
print("  size :", m.size)    # total de elementos
print("  dtype:", m.dtype)   # tipo de dato

dtype inferido: float64
dtype=int    : [1 2 3] → int64
dtype=complex: [1.+0.j 2.+0.j 3.+0.j] → complex128

x_int.astype(float): [1. 2. 3.] → float64

Array m:
[[1 2 3]
 [4 5 6]]
  ndim : 2
  shape: (2, 3)
  size : 6
  dtype: int64


---
## Nivel 2 — Indexación y Operaciones

### Acceder a elementos (indexación)

In [9]:
v = np.array([10, 20, 30, 40, 50])

print("Arreglo:", v)
print("Primer elemento (índice 0):", v[0])
print("Último elemento:", v[-1])
print("Elementos del índice 1 al 3:", v[1:4])
print("Cada dos elementos:", v[::2])

Arreglo: [10 20 30 40 50]
Primer elemento (índice 0): 10
Último elemento: 50
Elementos del índice 1 al 3: [20 30 40]
Cada dos elementos: [10 30 50]


In [10]:
# Indexación en matrices 2D
m = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Matriz:")
print(m)
print("\nElemento fila 0, columna 1:", m[0, 1])   # 2
print("Toda la primera fila:", m[0, :])            # [1, 2, 3]
print("Toda la segunda columna:", m[:, 1])         # [2, 5, 8]
print("\nSubmatriz (filas 0-1, columnas 1-2):")
print(m[0:2, 1:3])

Matriz:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Elemento fila 0, columna 1: 2
Toda la primera fila: [1 2 3]
Toda la segunda columna: [2 5 8]

Submatriz (filas 0-1, columnas 1-2):
[[2 3]
 [5 6]]


### Indexación booleana (filtrado)

In [11]:
notas = np.array([55, 72, 88, 45, 91, 63, 78])

print(notas[notas > 70])
# ¿Cuáles notas son mayores de 70?
aprobados = notas[notas > 70]
print("Todas las notas:", notas)
print("Notas > 70:", aprobados)
print("Cantidad de aprobados:", aprobados.shape[0])

# Condición compuesta
zona = notas[(notas >= 61) & (notas <= 70)]
print("Notas en zona (61-70):", zona)

[72 88 91 78]
Todas las notas: [55 72 88 45 91 63 78]
Notas > 70: [72 88 91 78]
Cantidad de aprobados: 4
Notas en zona (61-70): [63]


### Operaciones matemáticas

In [12]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print("a + b =", a + b)
print("a * b =", a * b)
print("b / a =", b / a)
print("a ** 2 =", a ** 2)  # Elevar al cuadrado
print("\nRaíz cuadrada de b:", np.sqrt(b))
print("e^a:", np.exp(a))

a + b = [11 22 33 44]
a * b = [ 10  40  90 160]
b / a = [10. 10. 10. 10.]
a ** 2 = [ 1  4  9 16]

Raíz cuadrada de b: [3.16227766 4.47213595 5.47722558 6.32455532]
e^a: [ 2.71828183  7.3890561  20.08553692 54.59815003]


### Broadcasting — reglas para operar arrays de distinta forma

Cuando aplicas una operación entre un array y un escalar (o dos arrays de forma distinta), NumPy ajusta los tamaños automáticamente siguiendo **dos reglas** (Stewart & Mommert, §4.1.4):

1. **Regla 1** — Si los arrays tienen distinto número de dimensiones, la forma del más pequeño se *extiende* a la izquierda con "1" hasta igualar.
2. **Regla 2** — Un eje de tamaño 1 se comporta como si tuviera el tamaño del eje más grande en esa dimensión (se "replica").

```
array   →  [1, 2, 3, 4, 5]   forma: (5,)
escalar →   10               forma: () → (1,) → (5,)   [reglas 1 y 2]
resultado→ [11, 12, 13, 14, 15]
```

Si dos ejes no son 1 y son distintos entre sí → **ValueError** (no se puede hacer broadcast).

In [13]:
v = np.array([1, 2, 3, 4, 5])

print("Array original:", v)
print("v + 10     :", v + 10)    # suma 10 a cada elemento
print("v * 3      :", v * 3)     # multiplica cada elemento por 3
print("v ** 2     :", v ** 2)    # eleva al cuadrado cada elemento
print("v / 2      :", v / 2)     # divide cada elemento entre 2
print("v - 1      :", v - 1)

# También funciona con matrices
m = np.array([[1, 2, 3],
              [4, 5, 6]])
print("\nMatriz + 100:")
print(m + 100)
print("\nMatriz * 2:")
print(m * 2)

Array original: [1 2 3 4 5]
v + 10     : [11 12 13 14 15]
v * 3      : [ 3  6  9 12 15]
v ** 2     : [ 1  4  9 16 25]
v / 2      : [0.5 1.  1.5 2.  2.5]
v - 1      : [0 1 2 3 4]

Matriz + 100:
[[101 102 103]
 [104 105 106]]

Matriz * 2:
[[ 2  4  6]
 [ 8 10 12]]


### Funciones matemáticas (ufuncs)

NumPy tiene versiones de las funciones matemáticas de `math` que funcionan directamente sobre **arrays completos** sin necesidad de un ciclo `for`. Estas se llaman *ufuncs* (universal functions).

In [14]:
x = np.array([0, 1, 2, 3, 4, 5])

print("x          :", x)
print("np.sqrt(x) :", np.sqrt(x))      # raíz cuadrada de cada elemento
print("np.exp(x)  :", np.exp(x))       # e^x
print("np.log(x+1):", np.log(x + 1))  # logaritmo natural (evitamos log(0))
print("np.abs(x-3):", np.abs(x - 3))  # valor absoluto
print("np.sign(x-3):", np.sign(x - 3)) # -1, 0 o 1 según el signo

x          : [0 1 2 3 4 5]
np.sqrt(x) : [0.         1.         1.41421356 1.73205081 2.         2.23606798]
np.exp(x)  : [  1.           2.71828183   7.3890561   20.08553692  54.59815003
 148.4131591 ]
np.log(x+1): [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
np.abs(x-3): [3 2 1 0 1 2]
np.sign(x-3): [-1 -1 -1  0  1  1]


In [15]:
# Funciones trigonométricas (el argumento está en radianes)
angulos = np.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2])

print("Ángulos (rad):", angulos.round(4))
print("sin          :", np.sin(angulos).round(4))
print("cos          :", np.cos(angulos).round(4))

# Caso práctico: calcular la componente vertical de lanzamientos
# con distintos ángulos y velocidad inicial v0 = 10 m/s
v0 = 10
v_vertical = v0 * np.sin(angulos)
print("\nVelocidad vertical (v0=10):", v_vertical.round(3))

Ángulos (rad): [0.     0.5236 0.7854 1.0472 1.5708]
sin          : [0.     0.5    0.7071 0.866  1.    ]
cos          : [1.     0.866  0.7071 0.5    0.    ]

Velocidad vertical (v0=10): [ 0.     5.     7.071  8.66  10.   ]


---
## Nivel 3b — Valores especiales y operadores lógicos

### Valores especiales: `nan` e `inf`

Algunas operaciones producen resultados especiales:
- `np.nan` (*Not a Number*): resultado indefinido, como `log(-1)` o `0/0`
- `np.inf` (*infinito*): resultado de dividir un número entre cero

NumPy tiene versiones de las funciones estadísticas que **ignoran** los `nan`:
`np.nanmean`, `np.nansum`, `np.nanmax`, `np.nanmin`

In [16]:
print("np.pi  =", np.pi)
print("np.e   =", np.e)
print("np.inf =", np.inf)
print("np.nan =", np.nan)

# nan aparece en operaciones indefinidas
x = np.array([-4.0, -1.0, 0.0, 1.0, 4.0])
print("\nsqrt de", x, "→", np.sqrt(x))   # sqrt de negativos → nan

# Funciones que ignoran nan
notas = np.array([85.0, np.nan, 72.0, np.nan, 91.0])
print("\nNotas con nan:", notas)
print("Media normal   :", np.mean(notas))       # ← devuelve nan
print("Media sin nan  :", np.nanmean(notas))    # ← ignora nan
print("Suma sin nan   :", np.nansum(notas))

np.pi  = 3.141592653589793
np.e   = 2.718281828459045
np.inf = inf
np.nan = nan

sqrt de [-4. -1.  0.  1.  4.] → [nan nan  0.  1.  2.]

Notas con nan: [85. nan 72. nan 91.]
Media normal   : nan
Media sin nan  : 82.66666666666667
Suma sin nan   : 248.0


/tmp/ipykernel_4814/3405442486.py:8: RuntimeWarning: invalid value encountered in sqrt
  print("\nsqrt de", x, "→", np.sqrt(x))   # sqrt de negativos → nan


### Operadores lógicos sobre arrays

Puedes comparar un array con un valor y obtienes un array de booleanos (`True`/`False`).
Luego ese array booleano puede usarse como filtro para seleccionar elementos.

In [17]:
temps = np.array([18.5, 22.0, 35.1, 15.3, 28.7, 12.0, 30.0])

# Comparación → array de True/False
print("Temperaturas:", temps)
print("temps > 25  :", temps > 25)

# Usar el array booleano para filtrar
calurosos = temps[temps > 25]
print("\nDías calurosos (> 25°C):", calurosos)

# Condición compuesta: & (y) , | (o)
moderados = temps[(temps >= 20) & (temps <= 30)]
print("Días moderados (20-30°C):", moderados)

# Contar cuántos cumplen la condición
print("\n¿Cuántos días > 25?:", np.sum(temps > 25))
print("¿Algún día < 10?  :", np.any(temps < 10))
print("¿Todos > 10?      :", np.all(temps > 10))

Temperaturas: [18.5 22.  35.1 15.3 28.7 12.  30. ]
temps > 25  : [False False  True False  True False  True]

Días calurosos (> 25°C): [35.1 28.7 30. ]
Días moderados (20-30°C): [22.  28.7 30. ]

¿Cuántos días > 25?: 3
¿Algún día < 10?  : False
¿Todos > 10?      : True


#### `np.where` — asignar valores según condición

`np.where(condición, valor_si_True, valor_si_False)` crea un array nuevo aplicando una regla a cada elemento. Es el equivalente vectorizado del operador ternario.

In [18]:
notas = np.array([55, 72, 88, 45, 91, 63, 78])

# Etiquetar cada nota como "Aprobado" o "Reprobado"
estados = np.where(notas >= 61, "Aprobado", "Reprobado")

for n, e in zip(notas, estados):
    print(f"  Nota {n:3d} → {e}")

# También funciona con números
# Reemplazar notas menores a 61 con 0 (para penalización)
penalizadas = np.where(notas >= 61, notas, 0)
print("\nNotas penalizadas:", penalizadas)

  Nota  55 → Reprobado
  Nota  72 → Aprobado
  Nota  88 → Aprobado
  Nota  45 → Reprobado
  Nota  91 → Aprobado
  Nota  63 → Aprobado
  Nota  78 → Aprobado

Notas penalizadas: [ 0 72 88  0 91 63 78]


### Copias vs Vistas (*views*) — diferencia crítica con listas

En NumPy existen **tres comportamientos** distintos al "asignar" un array:

| Operación | Resultado | Modifica original |
|---|---|---|
| `b = a` | **alias** — misma memoria | Sí |
| `b = a[1:4]` | **vista** (*view*) — misma memoria | **Sí** ⚠️ |
| `b = a.copy()` | **copia** — memoria nueva | No |

> **¡Diferencia clave con listas!** En Python, `l[1:4]` es siempre una copia. En NumPy, `a[1:4]` es una **vista** del array original — modificarla cambia el original. Esto es fuente frecuente de errores (Stewart & Mommert, §4.1.2).

In [19]:
original = np.array([1, 2, 3, 4, 5])

# ⚠ ALIAS — dos nombres, un solo array
alias = original
alias[0] = 999
print("Alias modifica 'original':", original)

# ⚠ VISTA (slice) — ¡diferente a listas Python!
original2 = np.array([1, 2, 3, 4, 5])
vista = original2[1:4]      # NO es copia — es vista
vista[0] = 777
print("Slice (vista) modifica 'original2':", original2)

# ✅ COPIA independiente — usa .copy()
original3 = np.array([1, 2, 3, 4, 5])
copia = original3.copy()
copia[0] = 999
print("Copia NO modifica 'original3':", original3)

Alias modifica 'original': [999   2   3   4   5]
Slice (vista) modifica 'original2': [  1 777   3   4   5]
Copia NO modifica 'original3': [1 2 3 4 5]


### Unir arrays — concatenate, hstack, vstack, stack

NumPy ofrece varias formas de unir arrays (Stewart & Mommert, §4.1.5):

- `np.concatenate()`: función **general** — une a lo largo de un eje existente.
- `np.hstack()`: atajo para unir **horizontalmente** (eje 1 en 2D, eje 0 en 1D).
- `np.vstack()`: atajo para unir **verticalmente** (eje 0).
- `np.stack()`: apila creando un **nuevo eje**.

In [20]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Función general: np.concatenate
print("concatenate:", np.concatenate((a, b)))
print("hstack     :", np.hstack((a, b)))   # equivalente para 1D

# Para matrices
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

print("\nvstack (apilar filas, axis=0):")
print(np.vstack((m1, m2)))

print("\nhstack (unir columnas, axis=1):")
print(np.hstack((m1, m2)))

print("\nstack — crea NUEVO eje (shape resultante: 2×2×2):")
apilado = np.stack((m1, m2), axis=0)
print(apilado)
print("Shape:", apilado.shape)

concatenate: [1 2 3 4 5 6]
hstack     : [1 2 3 4 5 6]

vstack (apilar filas, axis=0):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

hstack (unir columnas, axis=1):
[[1 2 5 6]
 [3 4 7 8]]

stack — crea NUEVO eje (shape resultante: 2×2×2):
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)


### Ordenar y buscar — `np.sort` y `np.argsort`

- `np.sort(x)` — retorna una **copia ordenada** (no modifica `x`).
- `np.argsort(x)` — retorna los **índices** que ordenarían `x`. Muy útil para ordenar arrays relacionados (e.g., ordenar nombres por nota) (Stewart & Mommert, §4.2.5).

In [21]:
notas = np.array([78, 45, 92, 61, 88, 34, 73])
print("Notas originales:", notas)

# np.sort — retorna una copia ordenada (no modifica el original)
print("Ordenadas (asc) :", np.sort(notas))
print("Ordenadas (desc):", np.sort(notas)[::-1])

# np.argsort — retorna los ÍNDICES que ordenarían el array
indices = np.argsort(notas)
print("\nÍndices (argsort):", indices)
print("Aplicando índices :", notas[indices])   # equivale a sort

# Caso práctico: obtener ranking de estudiantes
nombres = np.array(["Ana", "Carlos", "Diana", "Eduardo", "Fátima", "Gabriel", "Helena"])
ranking = np.argsort(notas)[::-1]   # mayor a menor
print("\nRanking:")
for pos, i in enumerate(ranking, 1):
    print(f"  {pos}. {nombres[i]}: {notas[i]}")

Notas originales: [78 45 92 61 88 34 73]
Ordenadas (asc) : [34 45 61 73 78 88 92]
Ordenadas (desc): [92 88 78 73 61 45 34]

Índices (argsort): [5 1 3 6 0 4 2]
Aplicando índices : [34 45 61 73 78 88 92]

Ranking:
  1. Diana: 92
  2. Fátima: 88
  3. Ana: 78
  4. Helena: 73
  5. Eduardo: 61
  6. Carlos: 45
  7. Gabriel: 34


### Suma acumulativa — `np.cumsum`

`np.cumsum` calcula la suma acumulada: cada elemento del resultado es la suma de todos los anteriores más el actual. Útil para calcular totales progresivos (gastos, puntajes acumulados, etc.).

In [22]:
puntos_por_nivel = np.array([100, 250, 180, 320, 210])

print("Puntos por nivel   :", puntos_por_nivel)
print("Puntos acumulados  :", np.cumsum(puntos_por_nivel))

# Ejemplo: gastos diarios y total acumulado
gastos = np.array([50, 120, 30, 85, 200, 45])
print("\nGastos diarios     :", gastos)
print("Total acumulado    :", np.cumsum(gastos))
print("Total de la semana :", np.sum(gastos))

Puntos por nivel   : [100 250 180 320 210]
Puntos acumulados  : [ 100  350  530  850 1060]

Gastos diarios     : [ 50 120  30  85 200  45]
Total acumulado    : [ 50 170 200 285 485 530]
Total de la semana : 530


---
## Nivel 3 — Estadística y Álgebra Lineal

### Funciones estadísticas

In [23]:
datos = np.array([23, 45, 12, 67, 34, 89, 56, 78, 90, 11])

print("Datos:", datos)
print("\n--- Estadísticas ---")
print(f"Mínimo:              {np.min(datos)}")
print(f"Máximo:              {np.max(datos)}")
print(f"Suma:                {np.sum(datos)}")
print(f"Media (promedio):    {np.mean(datos):.2f}")
print(f"Mediana:             {np.median(datos):.2f}")
print(f"Desviación estándar: {np.std(datos):.2f}")
print(f"Varianza:            {np.var(datos):.2f}")
print(f"\nÍndice del máximo:   {np.argmax(datos)}")
print(f"Índice del mínimo:   {np.argmin(datos)}")

Datos: [23 45 12 67 34 89 56 78 90 11]

--- Estadísticas ---
Mínimo:              11
Máximo:              90
Suma:                505
Media (promedio):    50.50
Mediana:             50.50
Desviación estándar: 28.64
Varianza:            820.25

Índice del máximo:   8
Índice del mínimo:   9


### Estadísticas avanzadas — histograma, media ponderada, correlación

- `np.histogram(x, bins)` — distribución de frecuencias (retorna conteo y bordes).
- `np.average(x, weights=w)` — **media ponderada** (cada dato tiene un peso diferente).
- `np.corrcoef(x, y)` — **coeficiente de correlación** de Pearson entre dos arrays.
- **API moderna de números aleatorios**: usar `default_rng(semilla)` en lugar de `np.random.seed()` (Stewart & Mommert, §4.4).

In [24]:
from numpy.random import default_rng
rng = default_rng(42)   # semilla para reproducibilidad

# Generar datos con distribución normal (media=70, desv=10)
calificaciones = rng.normal(loc=70, scale=10, size=200).clip(0, 100)

# np.histogram — distribución de frecuencias
conteo, bordes = np.histogram(calificaciones, bins=10)
print("Conteo por intervalo:", conteo)
print("Bordes de intervalos:", bordes.round(1))

# Media ponderada: notas con distintos pesos
mediciones = np.array([3.1, 2.7, 2.5, 3.1, 2.9])
incertidumbres = np.array([0.05, 0.15, 0.60, 0.10, 0.05])
print("\nMedia simple    :", np.mean(mediciones).round(4))
print("Media ponderada :", np.average(mediciones, weights=1/incertidumbres**2).round(4))
# Pesos = 1/σ² → mayor peso a mediciones más precisas

# Correlación entre dos arrays
x = np.array([1, 2, 3, 4, 5])
y = np.array([2.1, 3.9, 6.2, 7.8, 10.1])
print("\nCoeficiente de correlación Pearson:")
print(np.corrcoef(x, y).round(4))

Conteo por intervalo: [ 6 16 31 44 39 39 12  9  3  1]
Bordes de intervalos: [48.7 53.7 58.8 63.8 68.9 73.9 79.  84.  89.  94.1 99.1]

Media simple    : 2.86
Media ponderada : 2.995

Coeficiente de correlación Pearson:
[[1.     0.9987]
 [0.9987 1.    ]]


### Reshape — cambiar la forma de un array

In [25]:
# Crear un arreglo de 12 elementos y reorganizarlo
v = np.arange(1, 13)
print("Arreglo original:", v)
print("Forma:", v.shape)

# Convertir a matriz 3x4
m = v.reshape(3, 4)
print("\nReorganizado a 3x4:")
print(m)

# Convertir a matriz 2x6
print("\nReorganizado a 2x6:")
print(v.reshape(2, 6))

Arreglo original: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Forma: (12,)

Reorganizado a 3x4:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Reorganizado a 2x6:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


### Multiplicación de matrices y operaciones esenciales

| Operación | Sintaxis | Descripción |
|---|---|---|
| Elemento a elemento | `A * B` | Hadamard product |
| Matricial | `A @ B` o `np.matmul(A, B)` | Producto matricial |
| Transpuesta | `A.T` o `np.transpose(A)` | Intercambia filas↔columnas |
| Identidad | `np.identity(n)` | Matriz identidad n×n |
| Aplanar | `A.ravel()` o `np.ravel(A)` | Convierte a vector 1D |

In [26]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("A * B (elemento a elemento):")
print(A * B)

print("\nA @ B (multiplicación matricial):")
print(A @ B)

print("\nA.T (transpuesta):")
print(A.T)

print("\nnp.identity(3) — matriz identidad:")
print(np.identity(3))

# Aplanar una matriz a vector 1D
print("\nA.ravel() — aplanar a 1D:", A.ravel())

A * B (elemento a elemento):
[[ 5 12]
 [21 32]]

A @ B (multiplicación matricial):
[[19 22]
 [43 50]]

A.T (transpuesta):
[[1 3]
 [2 4]]

np.identity(3) — matriz identidad:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

A.ravel() — aplanar a 1D: [1 2 3 4]


---
## Nivel 3d — Álgebra Lineal (`numpy.linalg`)

NumPy incluye el módulo `numpy.linalg` (importado como `la`) para operaciones matriciales avanzadas (Stewart & Mommert, §4.7):

| Función | Descripción |
|---|---|
| `la.det(A)` | Determinante de A |
| `la.inv(A)` | Inversa de A (si det ≠ 0) |
| `la.norm(v)` | Norma euclidiana de un vector |
| `la.solve(A, b)` | Resuelve el sistema **Ax = b** |
| `la.eig(A)` | Eigenvalores y eigenvectores de A |

> `la.solve(A, b)` es numéricamente más estable y eficiente que calcular `la.inv(A) @ b`.

In [27]:
import numpy.linalg as la

A = np.array([[4, 2, 0],
              [9, 3, 7],
              [1, 2, 1]], dtype=float)

print("Matriz A:")
print(A)

# Determinante
print("\nDeterminante:", la.det(A).round(4))

# Inversa (si det ≠ 0)
A_inv = la.inv(A)
print("\nInversa A⁻¹:")
print(A_inv.round(4))

# Verificación: A @ A⁻¹ debe ser la identidad
print("\nA @ A⁻¹ (≈ identidad):")
print((A @ A_inv).round(10))

# Norma de un vector
v = np.array([3.0, 4.0])
print("\nNorma del vector [3, 4]:", la.norm(v))   # = 5.0

Matriz A:
[[4. 2. 0.]
 [9. 3. 7.]
 [1. 2. 1.]]

Determinante: -48.0

Inversa A⁻¹:
[[ 0.2292  0.0417 -0.2917]
 [ 0.0417 -0.0833  0.5833]
 [-0.3125  0.125   0.125 ]]

A @ A⁻¹ (≈ identidad):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Norma del vector [3, 4]: 5.0


In [28]:
import numpy.linalg as la

# ─── Resolución de sistemas de ecuaciones: Ax = b ───────────────────────────
# Ejemplo: sistema de 3 ecuaciones
#   3x + 2y +  z = 5
#   5x + 5y + 5z = 5
#    x + 4y + 6z = -3
A = np.array([[3, 2, 1],
              [5, 5, 5],
              [1, 4, 6]], dtype=float)
b = np.array([5, 5, -3], dtype=float)

x = la.solve(A, b)
print("Solución x:", x.round(4))
print("Verificación Ax - b ≈ 0:", (A @ x - b).round(10))

# ─── Eigenvalores y eigenvectores ───────────────────────────────────────────
print("\n--- Eigenvalores ---")
M = np.array([[-2, -4,  2],
              [-2,  1,  2],
              [ 4,  2,  5]], dtype=float)
eigenvalores, eigenvectores = la.eig(M)
print("Eigenvalores:", eigenvalores.round(3))
print("Primer eigenvector:", eigenvectores[:, 0].round(3))

Solución x: [ 1.  2. -2.]
Verificación Ax - b ≈ 0: [ 0.  0. -0.]

--- Eigenvalores ---
Eigenvalores: [-5.  3.  6.]
Primer eigenvector: [ 0.816  0.408 -0.408]


---
## Nivel 3e — Polinomios

NumPy permite representar polinomios por sus coeficientes y ofrece funciones para ajustar, evaluar y manipularlos (Stewart & Mommert, §4.6):

- `np.polyfit(x, y, deg)` — ajusta un polinomio de grado `deg` a datos *(x, y)* por mínimos cuadrados. Retorna los coeficientes `[a_n, ..., a_1, a_0]`.
- `np.polyval(coefs, x)` — evalúa el polinomio con coeficientes `coefs` en los puntos `x`.
- `np.poly(roots)` — construye coeficientes desde las raíces.
- `np.roots(coefs)` — calcula las raíces a partir de los coeficientes.

In [29]:
# Datos: velocidad inicial vs distancia máxima (proyectil simplificado)
# Queremos ajustar un polinomio de grado 2: d = a*v^2 + b*v + c
v = np.array([10, 20, 30, 40, 50], dtype=float)   # velocidad (m/s)
d = np.array([5.1, 20.4, 45.9, 81.6, 127.5])      # distancia (m)

# np.polyfit: ajuste de mínimos cuadrados
coefs = np.polyfit(v, d, deg=2)
print("Coeficientes [a, b, c]:", coefs.round(4))
print(f"Modelo: d = {coefs[0]:.4f}·v² + {coefs[1]:.4f}·v + {coefs[2]:.4f}")

# np.polyval: evaluar el polinomio en nuevos valores
v_nuevo = np.array([25, 35, 45])
d_pred = np.polyval(coefs, v_nuevo)
print("\nPredicciones:")
for vi, di in zip(v_nuevo, d_pred):
    print(f"  v={vi} m/s → d≈{di:.2f} m")

Coeficientes [a, b, c]: [ 0.051 -0.     0.   ]
Modelo: d = 0.0510·v² + -0.0000·v + 0.0000

Predicciones:
  v=25 m/s → d≈31.88 m
  v=35 m/s → d≈62.48 m
  v=45 m/s → d≈103.28 m


---
## Nivel 4 — Ejemplo Aplicado: Cálculo de Notas

In [30]:
# Simulación de notas de un curso
# Filas = estudiantes, Columnas = [Tarea1, Tarea2, Examen parcial, Examen final]
np.random.seed(42)  # Para reproducibilidad

notas = np.random.randint(40, 101, size=(8, 4))
pesos = np.array([0.15, 0.15, 0.30, 0.40])  # Pesos de cada evaluación

nombres = ["Ana", "Carlos", "Diana", "Eduardo", "Fátima", "Gabriel", "Helena", "Iván"]

print("Notas (Tarea1 | Tarea2 | Parcial | Final):")
print("-" * 50)
for nombre, fila in zip(nombres, notas):
    print(f"{nombre:<10} {fila}")

# Calcular nota final ponderada para cada estudiante
notas_finales = notas @ pesos

print("\n--- Resultados Finales ---")
for nombre, nota in zip(nombres, notas_finales):
    estado = "APROBADO" if nota >= 61 else "REPROBADO"
    print(f"{nombre:<10} Nota: {nota:.1f}  →  {estado}")

print(f"\nPromedio del curso: {np.mean(notas_finales):.2f}")
print(f"Nota más alta:      {np.max(notas_finales):.2f}")
print(f"Nota más baja:      {np.min(notas_finales):.2f}")
print(f"Aprobados: {np.sum(notas_finales >= 61)} / {len(notas_finales)}")

Notas (Tarea1 | Tarea2 | Parcial | Final):
--------------------------------------------------
Ana        [78 91 68 54]
Carlos     [ 82  47 100  60]
Diana      [78 97 58 62]
Eduardo    [50 50 63 92]
Fátima     [75 79 63 42]
Gabriel    [61 92 41 63]
Helena     [83 69 77 41]
Iván       [99 60 72 51]

--- Resultados Finales ---
Ana        Nota: 67.3  →  APROBADO
Carlos     Nota: 73.3  →  APROBADO
Diana      Nota: 68.5  →  APROBADO
Eduardo    Nota: 70.7  →  APROBADO
Fátima     Nota: 58.8  →  REPROBADO
Gabriel    Nota: 60.5  →  REPROBADO
Helena     Nota: 62.3  →  APROBADO
Iván       Nota: 65.8  →  APROBADO

Promedio del curso: 65.91
Nota más alta:      73.35
Nota más baja:      58.80
Aprobados: 6 / 8


## Tarea 4 — NumPy en Práctica

La programación se aprende haciendo, no leyendo. Esta tarea tiene dos partes:

**Parte 1 — Descarga y ejecuta** (obligatorio)
Descarga este notebook y ejecútalo celda por celda en tu computadora.  
Asegúrate de que todas las celdas corran sin errores antes de continuar.

**Parte 2 — Ejercicios** (obligatorio)  
Completa cada celda que dice `# TU CÓDIGO AQUÍ` con tu solución.  
Ejecuta la celda para verificar que el resultado es correcto.

**Entrega: 1 de mayo**  
Sube el notebook a tu repositorio de GitHub y envía el **link directo al archivo `.ipynb`**.
El notebook debe tener todas las celdas ya ejecutadas (con outputs visibles).

Ejemplo de link válido:  
`https://github.com/tu-usuario/tu-repo/blob/main/Numpy.ipynb`

### Ejercicio 1 — Crear y operar arrays

Crea un array con los números del 1 al 10 usando `np.arange`.  
Luego calcula e imprime:
- Cada número multiplicado por 5
- Solo los números pares (usa indexación booleana)
- La suma de todos los números

In [31]:
# TU CÓDIGO AQUÍ
import numpy as np

# 1. Crear el array con los números del 1 al 10
array_original = np.arange(1, 11)
print(f"Array original: {array_original}")

# 2. Cada número multiplicado por 5
multiplicados = array_original * 5
print(f"Multiplicados por 5: {multiplicados}")

# 3. Solo los números pares (indexación booleana)
# La condición es que el resto de la división por 2 sea 0
pares = array_original[array_original % 2 == 0]
print(f"Números pares: {pares}")

# 4. La suma de todos los números
suma_total = np.sum(array_original)
print(f"Suma de todos los números: {suma_total}")

Array original: [ 1  2  3  4  5  6  7  8  9 10]
Multiplicados por 5: [ 5 10 15 20 25 30 35 40 45 50]
Números pares: [ 2  4  6  8 10]
Suma de todos los números: 55


### Ejercicio 2 — Funciones matemáticas

Dado el array de ángulos en grados, conviértelos a radianes y calcula su seno.  
Fórmula: `radianes = grados * π / 180`

Ángulos: 0°, 30°, 45°, 60°, 90°, 180°

In [32]:
grados = np.array([0, 30, 45, 60, 90, 180])

# TU CÓDIGO AQUÍ
import numpy as np

# 1. Definir el array de grados
grados = np.array([0, 30, 45, 60, 90, 180])

# 2. Convertir a radianes usando la fórmula
# También podrías usar np.deg2rad(grados)
radianes = grados * np.pi / 180

# 3. Calcular el seno de los ángulos
senos = np.sin(radianes)

# Mostrar resultados
print(f"Grados:   {grados}")
print(f"Radianes: {radianes}")
print(f"Seno:     {senos}")

Grados:   [  0  30  45  60  90 180]
Radianes: [0.         0.52359878 0.78539816 1.04719755 1.57079633 3.14159265]
Seno:     [0.00000000e+00 5.00000000e-01 7.07106781e-01 8.66025404e-01
 1.00000000e+00 1.22464680e-16]


### Ejercicio 3 — Filtrado y estadísticas

Dada la lista de temperaturas diarias de un mes, calcula:
1. La temperatura promedio, mínima y máxima
2. Cuántos días superaron los 28°C
3. Las temperaturas de los días fríos (menores a 20°C)
4. Reemplaza con `np.where` las temperaturas menores a 15°C por exactamente 15.0 (temperatura mínima registrada)

In [34]:
temperaturas = np.array([
    22.1, 19.5, 31.2, 28.0, 17.3, 25.8, 30.1,
    14.2, 26.7, 23.4, 18.9, 32.0, 29.5, 21.1,
    16.8, 27.3, 24.6, 13.5, 20.0, 28.9, 33.1,
    15.7, 22.8, 19.0, 31.5, 26.2, 18.1, 29.8,
    12.4, 25.0
])

# TU CÓDIGO AQUÍ
import numpy as np

temperaturas = np.array([
    22.1, 19.5, 31.2, 28.0, 17.3, 25.8, 30.1,
    14.2, 26.7, 23.4, 18.9, 32.0, 29.5, 21.1,
    16.8, 27.3, 24.6, 13.5, 20.0, 28.9, 33.1,
    15.7, 22.8, 19.0, 31.5, 26.2, 18.1, 29.8,
    12.4, 25.0])

# 1. Estadísticas básicas
promedio = np.mean(temperaturas)
minima = np.min(temperaturas)
maxima = np.max(temperaturas)

print(f"Promedio: {promedio:.2f}°C")
print(f"Mínima: {minima}°C | Máxima: {maxima}°C")

# 2. Días que superaron los 28°C
# Usamos .sum() sobre la máscara booleana para contar los True
dias_calurosos = np.sum(temperaturas > 28)
print(f"Días que superaron los 28°C: {dias_calurosos}")

# 3. Temperaturas de los días fríos (< 20°C)
frios = temperaturas[temperaturas < 20]
print(f"Temperaturas frías: {frios}")

# 4. Reemplazo con np.where
# Sintaxis: np.where(condicion, valor_si_cumple, valor_si_no_cumple)
temperaturas_ajustadas = np.where(temperaturas < 15, 15.0, temperaturas)

print("\nTemperaturas tras el ajuste (mínimo 15°C):")
print(temperaturas_ajustadas)

Promedio: 23.48°C
Mínima: 12.4°C | Máxima: 33.1°C
Días que superaron los 28°C: 8
Temperaturas frías: [19.5 17.3 14.2 18.9 16.8 13.5 15.7 19.  18.1 12.4]

Temperaturas tras el ajuste (mínimo 15°C):
[22.1 19.5 31.2 28.  17.3 25.8 30.1 15.  26.7 23.4 18.9 32.  29.5 21.1
 16.8 27.3 24.6 15.  20.  28.9 33.1 15.7 22.8 19.  31.5 26.2 18.1 29.8
 15.  25. ]


### Ejercicio 4 — Matrices

Crea una matriz de 4×4 con valores del 1 al 16 usando `np.arange` y `reshape`.  
Luego:
1. Imprime la primera fila
2. Imprime la última columna
3. Imprime la submatriz de las 2 primeras filas y las 2 últimas columnas
4. Calcula la suma de cada fila (investiga `np.sum` con el parámetro `axis`)

In [36]:
# TU CÓDIGO AQUÍ
import numpy as np

# 1. Crear la matriz 4x4 del 1 al 16
matriz = np.arange(1, 17).reshape(4, 4)
print("Matriz completa:")
print(matriz)
print("-" * 20)

# 2. Imprimir la primera fila
# Índice 0 para las filas
primera_fila = matriz[0, :]
print(f"Primera fila: {primera_fila}")

# 3. Imprimir la última columna
# : selecciona todas las filas, -1 selecciona la última columna
ultima_columna = matriz[:, -1]
print(f"Última columna: {ultima_columna}")

# 4. Submatriz: 2 primeras filas (0:2) y 2 últimas columnas (2:4 o 2:)
submatriz = matriz[0:2, 2:]
print("Submatriz (2x2 superior derecha):")
print(submatriz)

# 5. Suma de cada fila (axis=1)
# axis=0 sumaría columnas, axis=1 suma filas
suma_filas = np.sum(matriz, axis=1)
print(f"Suma de cada fila: {suma_filas}")

Matriz completa:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
--------------------
Primera fila: [1 2 3 4]
Última columna: [ 4  8 12 16]
Submatriz (2x2 superior derecha):
[[3 4]
 [7 8]]
Suma de cada fila: [10 26 42 58]


### Ejercicio 5 — Suma acumulativa

Un estudiante anotó los puntos que obtuvo en cada una de las 8 tareas del curso.  
Calcula e imprime los puntos acumulados después de cada tarea para saber en qué momento superó 100, 200 y 300 puntos.

**Tip:** usa `np.cumsum` y filtra con indexación booleana.

In [37]:
puntos_tareas = np.array([45, 38, 52, 29, 61, 47, 55, 33])

# TU CÓDIGO AQUÍ
import numpy as np

puntos_tareas = np.array([45, 38, 52, 29, 61, 47, 55, 33])

# 1. Calcular los puntos acumulados
acumulados = np.cumsum(puntos_tareas)
print(f"Puntos acumulados tras cada tarea:\n{acumulados}")

# 2. Identificar cuándo se superan los hitos (100, 200, 300)
# Usamos indexación booleana para encontrar los valores que cumplen la condición
hitos = [100, 200, 300]

for hito in hitos:
    # Filtramos el array de acumulados
    supera_hito = acumulados[acumulados > hito]

    if supera_hito.size > 0:
        # El primer elemento del filtro es el momento exacto en que se superó
        primer_valor = supera_hito[0]
        # Buscamos en qué tarea ocurrió (índice + 1 para que sea humano)
        numero_tarea = np.where(acumulados == primer_valor)[0][0] + 1
        print(f"Superó los {hito} puntos en la tarea {numero_tarea} (Total: {primer_valor})")

Puntos acumulados tras cada tarea:
[ 45  83 135 164 225 272 327 360]
Superó los 100 puntos en la tarea 3 (Total: 135)
Superó los 200 puntos en la tarea 5 (Total: 225)
Superó los 300 puntos en la tarea 7 (Total: 327)


### Ejercicio 6 — Álgebra Lineal

El sistema de ecuaciones representa un balance de fuerzas en una estructura:

$$2F_1 + F_2 = 100$$
$$F_1 + 3F_2 + F_3 = 200$$
$$F_2 + 2F_3 = 150$$

Usando `numpy.linalg`:
1. Resuelve el sistema con `la.solve(A, b)` para encontrar $F_1$, $F_2$, $F_3$
2. Verifica la solución calculando `A @ x - b` (debe ser ≈ 0)
3. Calcula el determinante de A con `la.det(A)`
4. Calcula la norma de la solución `x` con `la.norm(x)`

In [38]:
import numpy.linalg as la

# Sistema de ecuaciones (balance de fuerzas en un puente):
# 2F1 +  F2        = 100
#  F1 + 3F2 +  F3 = 200
#        F2 + 2F3 = 150

A = np.array([[2, 1, 0],
              [1, 3, 1],
              [0, 1, 2]], dtype=float)
b = np.array([100, 200, 150], dtype=float)

# TU CÓDIGO AQUÍ
import numpy as np
import numpy.linalg as la

# Definición del sistema
A = np.array([[2, 1, 0],
              [1, 3, 1],
              [0, 1, 2]], dtype=float)

b = np.array([100, 200, 150], dtype=float)

# 1. Resolver el sistema para encontrar F1, F2, F3
x = la.solve(A, b)
F1, F2, F3 = x

print(f"Solución del sistema:")
print(f"F1 = {F1:.2f}")
print(f"F2 = {F2:.2f}")
print(f"F3 = {F3:.2f}")
print("-" * 30)

# 2. Verificar la solución (A @ x - b)
# El operador @ realiza la multiplicación de matrices
verificacion = A @ x - b
print(f"Verificación (A @ x - b): \n{verificacion}")
# Nota: Verás valores cercanos a e-15 o e-16, que es el cero computacional.

# 3. Calcular el determinante de A
determinante = la.det(A)
print(f"\nDeterminante de A: {determinante:.2f}")

# 4. Calcular la norma de la solución x
norma = la.norm(x)
print(f"Norma de la solución x: {norma:.2f}")

Solución del sistema:
F1 = 31.25
F2 = 37.50
F3 = 56.25
------------------------------
Verificación (A @ x - b): 
[0. 0. 0.]

Determinante de A: 8.00
Norma de la solución x: 74.48


### Ejercicio 7 — Polinomios (ajuste de curva)

Un objeto en caída libre sigue la ecuación $x(t) = \frac{1}{2}g t^2$.

Con los datos de tiempo y posición dados, usa `np.polyfit` para ajustar un polinomio de grado 2 y:
1. Muestra los coeficientes obtenidos
2. Estima la aceleración de gravedad `g` a partir del coeficiente cuadrático
3. Usa `np.polyval` para predecir la posición en `t = 2.5` s y `t = 6` s

**Pista:** el coeficiente de $t^2$ en el polinomio es $\frac{g}{2}$.

In [39]:
t = np.array([0, 1, 2, 3, 4, 5], dtype=float)         # tiempo (s)
pos = np.array([0.0, 4.9, 19.6, 44.1, 78.4, 122.5])   # posición (m)

# TU CÓDIGO AQUÍ
import numpy as np

# Datos experimentales
t = np.array([0, 1, 2, 3, 4, 5], dtype=float)         # tiempo (s)
pos = np.array([0.0, 4.9, 19.6, 44.1, 78.4, 122.5])   # posición (m)

# 1. Ajuste de polinomio de grado 2
# polyfit devuelve los coeficientes en orden descendente: [t^2, t^1, t^0]
coefs = np.polyfit(t, pos, 2)
a, b, c = coefs

print(f"Coeficientes obtenidos: {coefs}")
print(f"Ecuación ajustada: y = {a:.2f}t² + {b:.2f}t + {c:.2f}")
print("-" * 40)

# 2. Estimar la aceleración de gravedad (g)
# El coeficiente 'a' (el de t^2) corresponde a 1/2 * g
g_estimada = 2 * a
print(f"Aceleración de gravedad estimada (g): {g_estimada:.2f} m/s²")

# 3. Predicción con np.polyval
tiempos_prediccion = np.array([2.5, 6.0])
posiciones_predichas = np.polyval(coefs, tiempos_prediccion)

print(f"\nPredicciones de posición:")
for time, p in zip(tiempos_prediccion, posiciones_predichas):
    print(f"Para t = {time}s, la posición estimada es {p:.2f}m")

Coeficientes obtenidos: [ 4.90000000e+00 -1.24470554e-14  2.49582512e-14]
Ecuación ajustada: y = 4.90t² + -0.00t + 0.00
----------------------------------------
Aceleración de gravedad estimada (g): 9.80 m/s²

Predicciones de posición:
Para t = 2.5s, la posición estimada es 30.63m
Para t = 6.0s, la posición estimada es 176.40m
